### ISSUE TITLE
PRACTICA 8

### ISSUE THREAD

**Issue by Rufino07** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-rmsc#2]
[practica 8 cont.pdf](https://github.com/user-attachments/files/17649458/practica.8.cont.pdf)

**Comment by SANDRAVELASCO** [comment]
18/20 entrega fuera del sprint, el formato del reporte tiene errores que no se revisaron al momento de subirlo

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
